### ISSUE TITLE
Error pushing Eigen Hg repo to github

### ISSUE THREAD

**Issue by ibell** [schacon/hg-git#284]
I cloned Eigen with hg, Full traceback below:

What I tried to run:

```
hg clone https://bitbucket.org/eigen/eigen
cd eigen/
hg bookmark -r default master
hg push git+ssh://git@github.com/ibell/Eigen.git
```

which yields

```
** Python 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
** Mercurial Distributed SCM (version 2.8.2)
** Extensions loaded: hggit
Traceback (most recent call last):
  File "/usr/bin/hg", line 38, in <module>
    mercurial.dispatch.run()
  File "/usr/lib/python2.7/dist-packages/mercurial/dispatch.py", line 28, in run
    sys.exit((dispatch(request(sys.argv[1:])) or 0) & 255)
  File "/usr/lib/python2.7/dist-packages/mercurial/dispatch.py", line 69, in dispatch
    ret = _runcatch(req)
  File "/usr/lib/python2.7/dist-packages/mercurial/dispatch.py", line 133, in _runcatch
    return _dispatch(req)
  File "/usr/lib/python2.7/dist-packages/mercurial/dispatch.py", line 806, in _dispatch
    cmdpats, cmdoptions)
  File "/usr/lib/python2.7/dist-packages/mercurial/dispatch.py", line 585, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/usr/lib/python2.7/dist-packages/mercurial/dispatch.py", line 897, in _runcommand
    return checkargs()
  File "/usr/lib/python2.7/dist-packages/mercurial/dispatch.py", line 868, in checkargs
    return cmdfunc()
  File "/usr/lib/python2.7/dist-packages/mercurial/dispatch.py", line 803, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **cmdoptions)
  File "/usr/lib/python2.7/dist-packages/mercurial/util.py", line 512, in check
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mercurial/commands.py", line 4711, in push
    newbranch=opts.get('new_branch'))
  File "/usr/local/lib/python2.7/dist-packages/hggit/hgrepo.py", line 21, in push
    return self.githandler.push(remote.path, revs, force)
  File "/usr/local/lib/python2.7/dist-packages/hggit/git_handler.py", line 281, in push
    self.export_commits()
  File "/usr/local/lib/python2.7/dist-packages/hggit/git_handler.py", line 247, in export_commits
    self.export_git_objects()
  File "/usr/local/lib/python2.7/dist-packages/hggit/git_handler.py", line 390, in export_git_objects
    self.export_hg_commit(rev, exporter)
  File "/usr/local/lib/python2.7/dist-packages/hggit/git_handler.py", line 455, in export_hg_commit
    for obj, nodeid in exporter.update_changeset(ctx):
  File "/usr/local/lib/python2.7/dist-packages/hggit/hg2git.py", line 163, in update_changeset
    self._remove_path(path, dirty_trees)
  File "/usr/local/lib/python2.7/dist-packages/hggit/hg2git.py", line 208, in _remove_path
    del tree[os.path.basename(path)]
  File "/usr/local/lib/python2.7/dist-packages/dulwich/objects.py", line 866, in __delitem__
    del self._entries[name]
KeyError: 'Core'
```

**Comment by nschloe** [comment]
Curiously, I'm getting the exact same error message (for the same repo, too). Any updates here?
