### ISSUE TITLE
Failure to clone with git+https:// addresses

### ISSUE THREAD

**Issue by planetmaker** [schacon/hg-git#292]
It fails to clone from URLs from github with the prefix git+https:// - but the very same URL works as git://

$ hg clone git+https://github.com/KonradIT/autoexechack
Zielverzeichnis: autoexechack
** Unknown exception encountered with possibly-broken third-party extension hggit
** which supports versions 3.2 of Mercurial.
** Please disable hggit and try your action again.
** If that fixes the bug please report it to https://bitbucket.org/durin42/hg-git/issues
** Python 2.7.6 (default, Jan 11 2014, 14:34:26) [GCC 4.8.2]
** Mercurial Distributed SCM (Version 3.3-rc)
** Erweiterungen geladen: color, purge, convert, hggit, rebase, record, evolve, strip, mq, shelve
Traceback (most recent call last):
  File "/home/ingo/bin/mercurial/hg/hg", line 43, in <module>
    mercurial.dispatch.run()
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 28, in run
    sys.exit((dispatch(request(sys.argv[1:])) or 0) & 255)
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 71, in dispatch
    ret = _runcatch(req)
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 140, in _runcatch
    return _dispatch(req)
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 860, in _dispatch
    cmdpats, cmdoptions)
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 621, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/home/ingo/bin/mercurial/hg/mercurial/extensions.py", line 196, in wrap
    return wrapper(origfn, *args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/hgext/color.py", line 491, in colorcmd
    return orig(ui_, opts, cmd, cmdfunc)
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 951, in _runcommand
    return checkargs()
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 922, in checkargs
    return cmdfunc()
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 857, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **cmdoptions)
  File "/home/ingo/bin/mercurial/hg/mercurial/util.py", line 711, in check
    return func(*args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/commands.py", line 1374, in clone
    branch=opts.get('branch'))
  File "/home/ingo/bin/mercurial/hg/mercurial/hg.py", line 434, in clone
    destpeer.local().clone(srcpeer, heads=revs, stream=stream)
  File "/home/ingo/bin/mercurial/hg/mercurial/localrepo.py", line 1792, in clone
    ret = exchange.pull(self, remote, heads).cgresult
  File "/home/ingo/bin/mercurial/hg/mercurial/extensions.py", line 196, in wrap
    return wrapper(origfn, *args, **kwargs)
  File "/home/ingo/bin/mercurial/hg-git/hggit/util.py", line 42, in inner
    return f(*args, **kwargs)
  File "/home/ingo/bin/mercurial/hg-git/hggit/__init__.py", line 233, in exchangepull
    pullop.cgresult = repo.githandler.fetch(remote.path, heads)
  File "/home/ingo/bin/mercurial/hg-git/hggit/git_handler.py", line 231, in fetch
    refs = self.fetch_pack(remote, heads)
  File "/home/ingo/bin/mercurial/hg-git/hggit/git_handler.py", line 1042, in fetch_pack
    client, path = self.get_transport_and_path(remote_name)
  File "/home/ingo/bin/mercurial/hg-git/hggit/git_handler.py", line 1496, in get_transport_and_path
    return client.HttpGitClient(uri, opener=opener), uri
  File "/usr/lib/python2.7/dist-packages/dulwich/client.py", line 637, in __init__
    GitClient.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'opener'

**Comment by planetmaker** [comment]
The issue still persists, and also appears for pull and in hg 3.3.3 with hg-git 0.8.0:
ingo@aeolus ~/el/elhg $ LC_ALL=C hg pull git+https://github.com/raduprv/Eternal-Lands.git
pulling from git+https://github.com/raduprv/Eternal-Lands.git
** unknown exception encountered, please report by visiting
** http://mercurial.selenic.com/wiki/BugTracker
** Python 2.7.6 (default, Jan 11 2014, 14:34:26) [GCC 4.8.2]
** Mercurial Distributed SCM (version 3.3.3)
** Extensions loaded: color, purge, convert, patchbomb, hggit, rebase, record, evolve, strip, mq, shelve
Traceback (most recent call last):
  File "/home/ingo/bin/mercurial/hg/hg", line 43, in <module>
    mercurial.dispatch.run()
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 28, in run
    sys.exit((dispatch(request(sys.argv[1:])) or 0) & 255)
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 71, in dispatch
    ret = _runcatch(req)
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 140, in _runcatch
    return _dispatch(req)
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 863, in _dispatch
    cmdpats, cmdoptions)
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 624, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/home/ingo/bin/mercurial/hg/mercurial/extensions.py", line 194, in wrap
    return wrapper(origfn, *args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/hgext/color.py", line 491, in colorcmd
    return orig(ui_, opts, cmd, cmdfunc)
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 954, in _runcommand
    return checkargs()
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 925, in checkargs
    return cmdfunc()
  File "/home/ingo/bin/mercurial/hg/mercurial/dispatch.py", line 860, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **cmdoptions)
  File "/home/ingo/bin/mercurial/hg/mercurial/util.py", line 711, in check
    return func(*args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/extensions.py", line 149, in wrap
    util.checksignature(origfn), *args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/util.py", line 711, in check
    return func(*args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/hgext/mq.py", line 3483, in mqcommand
    return orig(ui, repo, *args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/util.py", line 711, in check
    return func(*args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/extensions.py", line 149, in wrap
    util.checksignature(origfn), *args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/util.py", line 711, in check
    return func(*args, **kwargs)
  File "/home/ingo/bin/mercurial/mutable-history/hgext/evolve.py", line 596, in warnobserrors
    ret = orig(ui, repo, *args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/util.py", line 711, in check
    return func(*args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/extensions.py", line 149, in wrap
    util.checksignature(origfn), *args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/util.py", line 711, in check
    return func(*args, **kwargs)
  File "/home/ingo/bin/mercurial/mutable-history/hgext/evolve.py", line 574, in wrapmayobsoletewc
    res = origfn(ui, repo, *args, **opts)
  File "/home/ingo/bin/mercurial/hg/mercurial/util.py", line 711, in check
    return func(*args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/extensions.py", line 149, in wrap
    util.checksignature(origfn), *args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/util.py", line 711, in check
    return func(*args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/hgext/rebase.py", line 1048, in pullrebase
    orig(ui, repo, *args, **opts)
  File "/home/ingo/bin/mercurial/hg/mercurial/util.py", line 711, in check
    return func(*args, **kwargs)
  File "/home/ingo/bin/mercurial/hg/mercurial/commands.py", line 4993, in pull
    remotebookmarks = other.listkeys('bookmarks')
  File "/home/ingo/bin/mercurial/hg-git/hggit/gitrepo.py", line 51, in listkeys
    refs = handler.fetch_pack(self.path, heads=[])
  File "/home/ingo/bin/mercurial/hg-git/hggit/git_handler.py", line 1042, in fetch_pack
    client, path = self.get_transport_and_path(remote_name)
  File "/home/ingo/bin/mercurial/hg-git/hggit/git_handler.py", line 1496, in get_transport_and_path
    return client.HttpGitClient(uri, opener=opener), uri
  File "/usr/lib/python2.7/dist-packages/dulwich/client.py", line 637, in __init__
    GitClient.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'opener'
