### ISSUE TITLE
Failed push to GitHub - abort: error: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by jambrothers** [schacon/hg-git#324]
The error message in the subject is from non-verbose mode. With verbose = True, the following traceback is printed:

```
** unknown exception encountered, please report by visiting
** https://mercurial-scm.org/wiki/BugTracker
** Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
** Mercurial Distributed SCM (version 4.3.1)
** Extensions loaded: hggit, churn
Traceback (most recent call last):
  File "hg", line 61, in <module>
  File "mercurial\dispatch.pyo", line 81, in run
  File "mercurial\dispatch.pyo", line 162, in dispatch
  File "mercurial\dispatch.pyo", line 302, in _runcatch
  File "mercurial\dispatch.pyo", line 310, in _callcatch
  File "mercurial\scmutil.pyo", line 150, in callcatch
  File "mercurial\dispatch.pyo", line 292, in _runcatchfunc
  File "mercurial\dispatch.pyo", line 896, in _dispatch
  File "mercurial\dispatch.pyo", line 658, in runcommand
  File "mercurial\dispatch.pyo", line 904, in _runcommand
  File "mercurial\dispatch.pyo", line 893, in <lambda>
  File "mercurial\util.pyo", line 1077, in check
  File "mercurial\commands.pyo", line 4065, in push
  File "mercurial\extensions.pyo", line 322, in closure
  File "hggit\util.pyo", line 56, in inner
  File "hggit\__init__.pyo", line 373, in exchangepush
  File "hggit\git_handler.pyo", line 396, in push
  File "hggit\git_handler.pyo", line 1422, in update_remote_branches
  File "dulwich\refs.pyo", line 279, in __setitem__
  File "dulwich\refs.pyo", line 597, in set_if_equals
  File "dulwich\refs.pyo", line 180, in _check_refname
dulwich.errors.RefFormatError: refs/remotes/default:pushurl/master
```
I'm not sure what can be done to fix the problem?

**Comment by jelmer** [comment]
hg-git should probably mangle/strip the spaces before using them in ref names.
